version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p geheim"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - mynetwork

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork

networks:
  mynetwork:
